version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./volumes/wordpress:/var/www/html
    - ./logs/nginx:/var/log/nginx
    depends_on:
    - wordpress
    networks:
    - tenup-scaffold-net
  wordpress:
    image: wordpress:php7.1-fpm
    volumes:
    - ./volumes/wordpress:/var/www/html
    - ./plugin.php:/var/www/html/wp-content/plugins/tenup-scaffold/tenup-scaffold.php
    - ./includes:/var/www/html/wp-content/plugins/tenup-scaffold/includes
    - ./languages:/var/www/html/wp-content/plugins/tenup-scaffold/languages
    - ./dist:/var/www/html/wp-content/plugins/tenup-scaffold/dist
    - ./docker/wordpress/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./logs/fpm:/var/log/fpm
    depends_on:
    - mysql
    networks:
    - tenup-scaffold-net
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    # <Port exposed> : < MySQL Port running inside container>
    - '3306:3306'
    expose:
    # Opens port 3306 on the container
    - '3306'
    # Where our data will be persisted
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    command: --innodb-use-native-aio=0 --ignore-db-dir=lost+found
    networks:
    - tenup-scaffold-net


networks:
  tenup-scaffold-net:
    driver: bridge